name: Deploy container to Azure

on: 
  push:
    branches: ["main"]

jobs:
  build_image:
    runs-on: ubuntu-22.04
    steps:    
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2        

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devolsun:latest,${{ secrets.DOCKERHUB_USERNAME }}/devolsun:${{ github.sha }}
    
  deploy:
    runs-on: ubuntu-22.04
    needs: build_image
    environment:
      name: 'production'
      url: ${{steps.deploy-to-webapp.outputs.webapp-url}}
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'devOlsun'
          slot-name: 'production'
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          images: ${{ secrets.DOCKER_HUB_USERNAME }}/devolsun:${{ github.sha }}